readonly DEFAULT_UBUNTU_VERSION=20.04
export UBUNTU_VERSION=${UBUNTU_VERSION:-$DEFAULT_UBUNTU_VERSION}

readonly DEFAULT_DPDK_VERSION=21.05
export DPDK_VERSION=${DPDK_VERSION:-$DEFAULT_DPDK_VERSION}

export IMAGE_NAME=quay.io/alexanderfefelov/dpdk
